name: Build and Publish Kibana to GHCR

on:
  push:
    branches:
      - openai_pki_connector_8_15
  pull_request:
    branches:
      - openai_pki_connector_8_15

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: openai_pki_connector_8_15

      - name: Read Node.js Version from .node-version
        id: node_version
        run: echo "NODE_VERSION=$(cat .node-version | tr -d '[:space:]')" >> $GITHUB_ENV

      - name: Set up Node.js and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y tar gzip build-essential python3

      - name: Bootstrap Kibana
        run: yarn kbn bootstrap

      - name: Build Kibana (Only for Linux x86_64)
        run: |
          yarn build --release --skip-os-packages --skip-archives="darwin-x86_64,darwin-aarch64,windows-x86_64,linux-aarch64"

      - name: Locate Dockerfile
        run: |
          if [ -f build/default/Dockerfile ]; then
            echo "Using Dockerfile at build/default/Dockerfile"
            echo "DOCKERFILE_PATH=build/default/Dockerfile" >> $GITHUB_ENV
          else
            echo "ERROR: Dockerfile not found in expected location!"
            exit 1
          fi

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/kibana:8.15 -f ${{ env.DOCKERFILE_PATH }} .

      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/kibana:8.15
