name: Build and Publish Kibana to GHCR

on:
  push:
    branches:
      - openai_pki_connector_8_15  # Only runs on your development branch
  pull_request:
    branches:
      - openai_pki_connector_8_15  # Runs on PRs within your fork only

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Read Node.js Version from .node-version
        id: node_version
        run: echo "NODE_VERSION=$(cat .node-version | tr -d '[:space:]')" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y tar gzip build-essential python3 libvips-dev

      - name: Bootstrap Kibana
        run: yarn kbn bootstrap

      - name: Build Kibana
        run: yarn build --release --skip-os-packages

      - name: Ensure Required Files Exist
        run: |
          echo "Checking required build artifacts..."
          if [ ! -f "target/kibana-8.15.6-linux-x86_64.tar.gz" ]; then
            echo "ERROR: kibana-8.15.6-linux-x86_64.tar.gz is missing in target/!"
            exit 1
          fi
          echo "All required files are present."

      - name: Locate Dockerfile
        run: |
          if [ -f build/kibana-docker/default/Dockerfile ]; then
            echo "Using Dockerfile at build/kibana-docker/default/Dockerfile"
            echo "DOCKERFILE_PATH=build/kibana-docker/default/Dockerfile" >> $GITHUB_ENV
          else
            echo "ERROR: Dockerfile not found in expected locations!"
            exit 1
          fi

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/kibana:8.15.6 -f $DOCKERFILE_PATH .

      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/kibana:8.15.6
